<div class="container">
	<div class="row">
		<div class="card col-md-12">
			<div class="card-body">
				<h3>Sejarah</h3>
				<p>Sejarah pendidikan Islam di Indonesia telah dimulai pada awal abad XX M hingga dewasa ini merupakan perjalanan yang cukup panjang. Dimana perkembangan cukup draktis terjadi pada masa orde lama dan terus berkembang pada masa orde baru.</p>
				<div class="cmsmasters_text">
					<p>Sejarah pendidikan Islam di Indonesia telah dimulai pada awal abad XX M hingga dewasa ini merupakan perjalanan yang cukup panjang. Dimana perkembangan cukup draktis terjadi pada masa orde lama dan terus berkembang pada masa orde baru.</p>
					<p><strong>Orde Lama</strong></p>
					<p>Setelah Indonesia merdeka, pendidikan agama telah mendapat perhatian serius dari pemerintah, baik di sekolah negeri maupun swasta. Usaha tersebut dimulai dengan memberikan bantuan sebagaimana anjuran oleh Badan Pekerja Komite Nasional Pusat (BPKNP) tanggal 27 Desember 1945, disebutkan :</p>
					<p>“<em>Madrasah dan pesantren yang pada hakikatnya adalah satu sumber pendidikan dan pencerdasan rakyat jelata yang telah berurat dan berakar dalam masyarakat Indonesia pada umumnya, hendaknya mendapatkan perhatian dan bantuan nyata berupa tuntunan dan bantuan material dari pemerintah</em>“</p>
					<p><strong>Pendidikan Agama diatur secara khusus dalam UU No, 4 Tahun 1950</strong>&nbsp;pada bab&nbsp;XII&nbsp;Pasal 20, yaitu :</p>
					<ol>
						<li>Di sekolah-sekolah negeri diadakan pelajaran agama, orang tua murid menetapkan apakah anaknya akan mengikuti pelajaran tersebut atau tidak.</li>
						<li>Cara penyelenggaraan pendidikan agama di sekolah negeri diatur dalam peraturan yang ditetapkan oleh Menteri Pendidikan Pengajaran dan Kebudayaan, bersama-sama dengan Menteri Agama.</li>
					</ol>
					<p>Perkembangan pendidikan Islam pada masa orde lama sangat terkait pula dengan peran&nbsp;<strong>Departemen Agama yang mulai resmi berdiri pada tanggal 3 Januari 1946</strong>. Departemen Agama sebagai suatu lembaga pada masa itu, secara intensif memperjuangkan politik pendidikan Islam di Indonesia.&nbsp;<strong>Pendidikan Islam pada masa itu ditangani oleh suatu bagian khusus yang mengurus masalah pendidikan agama, yaitu Bagian Pendidikan Agama.</strong>&nbsp;Tugas dari bagian tersebut sesuai dengan salah satu nota Islamic education in Indonesia yang disusun oleh Bagian Pendidikan Departemen Agama pada tanggal 1 September 1956, yaitu : 1) memberi pengajaran agama di sekolah negeri dan partikulir, 2) memberi pengetahuan umum di madrasah, dan 3)mengadakan Pendidikan Guru Agama serta Pendidikan Hakim Islam Negeri.</p>
					<p>Berdasarkan keterangan di atas, ada 2 hal yang penting berkaitan dengan pendidikan Islam pada masa orde lama, yaitu pengembangan dan pembinaan madrasah dan pendidikan Islam di sekolah umum.</p>
					<p><strong>Pendidikan Diniyah dan Pondok Pesantren</strong></p>
					<p>Pondok Pesantren sebagai bagian dari sistem pendidikan Nasional, keberadaan pondok pesantren sebelum Indonesia merdeka diperhitungkan oleh bangsa-bangsa yang pernah menjajah Indonesia.</p>
					<p><strong>Pada masa kolonialisme</strong>&nbsp;dari Pondok Pesantren lahirlah tokoh-tokoh nasional yang tangguh yang menjadi pelopor pergerakan kemerdekaan Indonesia, seperti&nbsp;KH.&nbsp;Hasyim Asyari,&nbsp;KH.&nbsp;Ahmad Dahlan,&nbsp;KH.&nbsp;Zaenal Mustopa dll. Maka dapat dikatakan bahwa masa itu Pondok Pesantren memberikan kontribusi yang besar bagi terbentunya republik ini. Bila dianalisis lebih jauh kenapa dari lembaga pendidikan yang sangat sederhana ini muncul tokoh-tokoh nasional yang mampu menggerakan rakyat untuk melawan penjajah, jawabannya karena figur Kiyai sebagai Pimpinan pondok pesantren sangat dihormati dan disegani, baik oleh komunitas pesantren (santri) maupun masyarakat sekitar pondok, mereka meyakini bahwa apa yang diucapkan kiyai adalah wahyu Tuhan yang mengandung nilai-nilai kebenaran hakiki ( Ilahiyyah).</p>
					<p><strong>Pada masa pasca kemerdekaan</strong>, Pondok Pesantren perkembangannya mengalami pasang surut dalam mengemban misinya sebagai pencetak generasi kaum muslimin yang mumpuni dalam bidang Agama (tafaqquh fiddien). Pada masa priode transisi antara tahun 1950 – 1965 Pondok Pesantren mengalami fase stagnasi, dimana Kyai yang disimbolkan sebagai figur yang ditokohkan oleh seluruh elemen masyarakat Islam, terjebak pada percaturan politik praktis, yang ditandai dengan bermunculannya partai politik bernuasa Islami pesertaPEMILU&nbsp;pertama tahun 1955, contohnya dengan lahirnya Partai Politik NU yang mewaliki warga Nahdiyyin, Partai Politik NU tersebut dapat dikatakan merepresentasikan dunia Pondok Pesantren. Hal ini dikarenakan sebagian besar pengurus dari parpol tersebut adalah Kiyai yang mempunyai Pondok Pesantren.</p>
					<p><strong>Orde Baru dan Sekarang</strong></p>
					<p>Perkembangan pendidikan Pondok Pesantren pada periode Orde Baru, seakan tenggelam eksistensinya karena seiring dengan kebijakan pemerintah yang kurang berpihak pada kepentingan ummat Islam.</p>
					<p>Setitik harapan timbul untuk nasib umat Islam setelah terjadinya era reformasi, pondok pesantren mulai berbenah diri lagi dan mendapatkan tempat lagi dikalangan pergaulan nasional. Salah satunya adalah<strong>pendidikan Pondok Pesantren diakui oleh pemerintah menjadi bagian dari sistem pendidikan nasional yang termaktub dalam Undang-Undang Sistem Pendidikan Nasional (Sisdiknas)</strong>. Pondok pesantren tidak lagi dipandang sebagai lembaga pendidikan tradisional yang illegal, namun pesantren diakui oleh pemerintah sebagai lembaga pendidikan yang mempunyai kesetaraan dalam hak dan kewajibannya dengan lembaga pendidikan formal lainnya.</p>
					<p>Peluang tersebut seharusnya dapat dimanfaatkan secara maksimal oleh seluruh Pondok Pesantren, agar dapat meningkatkan kembali peranannya dalam sistem pendidikan nasional. Namun yang terjadi peluang tersebut belum memberikan respon positif kearah peningkatan kualitas pendidikannya, salah satunya dapat diidentifikasikan bahwa hanya segelintir kecil saja masyarakat yang ingin menitipkan anaknya untuk dididik dilembaga pendidikan pondok pesantren, dibanding ke sekolah-sekolah umum. Ketimpangannya cukup besar, mungkin hanya 10% nya saja anak-anak Indonesia yang mengenyam pendidikan di pondok pesantren dan selebihnya mereka mengenyam pendidikan disekolah-sekolah umum.</p>
					<p>Pembinaan Pondok Pesantren sebelum tahun 2000 dilakukan oleh salah satu Subdit di lingkungan Direktorat Pembinaan Perguruan Agama Islam, yaitu&nbsp;<strong>Subdit Pondok Pesantren</strong>&nbsp;sesuai dengan Keputusan Menteri Agama Nomor 6 Tahun 1979.</p>
					<p>Akhirnya dengan makin pesatnya perkembangan lembaga pondok pesantren dan pendidikan diniyah serta makin berkembangnya program dan kegiatan pembinaan bagi Pondok Pesantren dan Pendidikan Diniyah, subdit tersebut berkembang menjadu direktorat yang bernama&nbsp;<strong>Direktorat Pendidikan Keagamaan dan Pondok Pesantren</strong>, sebagai satu dari empat direktorat yang pada Ditjen Kelembagaan Agama Islam sesuai Keputusan Menteri Agama Nomor 1 Tahun 2001. Dengan berubahnya organisasi pembinaan menjadi direktorat tersebut, maka pendidikan di pondok pesantren dan pendidikan diniyah terus makin berkembang dengan pesat, dan mulai diakui dikalangan dunia pendidikan.</p>
					<p>Pada akhirnya seiring dengan berkembangnya pembinaan dan pengorganisasian Direktorat Jenderal Kelembagaan Agama Islam yang berubah menjadi Direktorat Jenderal Pendidikan Islam, Direktorat Pendidikan Keagamaan dan Pondok Pesantren berubah pula menjadi&nbsp;<strong>Direktorat Pendidikan Diniyah dan Pondok Pesantren</strong>. Perubahan itu berdasarkan&nbsp;<strong>Peraturan Menteri Agama RI Nomor 3 Tahun 2006 sebagai tindak lanjut dari Peraturan Presiden Republik Indonesia Nomor 63 Tahun 2005 tentang Perubahan Peraturan Presiden Nomor 10 Tahun 2005.</strong></p>
				</div>
			</div>
		</div>
	</div>
</div>
